DROP DATABASE IF EXISTS db_projeto_integrador;
CREATE DATABASE IF NOT EXISTS db_projeto_integrador
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

USE db_projeto_integrador;

CREATE TABLE Categoria(
	IdCategoria INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    genero VARCHAR(255) NOT NULL,
    formato ENUM('Livro Digital','Livro Fisico') NOT NULL,
    classificacão VARCHAR(255) NOT NULL
);

CREATE TABLE Livros(
	IdProduto INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	titulo VARCHAR(255) NOT NULL,
	descricao VARCHAR(255) NOT NULL,
	preco DECIMAL(10,2) NOT NULL,
	autor VARCHAR(255) NOT NULL,
    IdCategoria INT UNSIGNED NOT NULL
);

CREATE TABLE Usuarios(
	IdCliente INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nome_User VARCHAR(100) NOT NULL,
	email_User VARCHAR(255) UNIQUE NOT NULL,
	senha_User VARCHAR(255) NOT NULL
);

ALTER TABLE Livros ADD CONSTRAINT FK_IdCategoria
FOREIGN KEY (IdCategoria)
REFERENCES Categoria (IdCategoria)
ON DELETE CASCADE
ON UPDATE CASCADE;